# Generated by Django 6.0.4 on 2026-05-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.CharField(max_length=10, unique=True, verbose_name='N° Place')),
                ('level', models.CharField(max_length=20, verbose_name='Niveau')),
                ('space_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('handicap', 'Handicapé'), ('reserved', 'Réservé')], default='standard', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupée'), ('reserved', 'Réservée'), ('maintenance', 'En maintenance')], default='available', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Place de parking',
                'verbose_name_plural': 'Places de parking',
                'ordering': ['space_number'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=20, verbose_name='Immatriculation')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='Type de véhicule')),
                ('subscription_type', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annual', 'Annuel')], default='monthly', max_length=20, verbose_name="Type d'abonnement")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('monthly_fee', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tarif mensuel (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='parking.parkingspace', verbose_name='Place')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_subscriptions', to='tenants.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Abonnement parking',
                'verbose_name_plural': 'Abonnements parking',
                'ordering': ['-start_date'],
            },
        ),
    ]
