# Generated by Django 6.0.4 on 2026-05-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du département')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('position', models.CharField(max_length=100, verbose_name='Poste')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('interim', 'Intérimaire'), ('stage', 'Stagiaire')], default='cdi', max_length=20, verbose_name='Type de contrat')),
                ('salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Salaire (FCFA)')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('on_leave', 'En congé'), ('terminated', 'Licencié')], default='active', max_length=20, verbose_name='Statut')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence")),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Tél. urgence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
