# Generated by Django 6.0.4 on 2026-06-04 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_mall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_accountant',
            field=models.BooleanField(default=False, verbose_name='Gère la comptabilité (Comptable)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_maintenance',
            field=models.BooleanField(default=False, verbose_name='Gère la maintenance (Technicien)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_secretary',
            field=models.BooleanField(default=False, verbose_name='Gère le secrétariat (Secrétaire)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur lié'),
        ),
    ]
