# Generated by Django 6.0.4 on 2026-06-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('accountant', 'Comptable'), ('maintenance', 'Agent de Maintenance'), ('employee', 'Employé')], default='employee', max_length=20),
        ),
    ]
