# Generated by Django 6.0.4 on 2026-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('accountant', 'Comptable'), ('maintenance', 'Agent de Maintenance'), ('secretary', 'Secrétaire'), ('employee', 'Employé')], default='employee', max_length=20),
        ),
    ]
