# Generated by Django 6.0.4 on 2026-05-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('salary', 'Salaires'), ('energy', 'Énergie & Eau'), ('security', 'Sécurité'), ('cleaning', 'Nettoyage'), ('insurance', 'Assurance'), ('taxes', 'Taxes & Impôts'), ('marketing', 'Marketing'), ('equipment', 'Équipement'), ('other', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Reçu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='N° Facture')),
                ('invoice_type', models.CharField(choices=[('rent', 'Loyer'), ('charges', 'Charges'), ('parking', 'Parking'), ('penalty', 'Pénalité'), ('other', 'Autre')], default='rent', max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('status', models.CharField(choices=[('paid', 'Payée'), ('pending', 'En attente'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.shop', verbose_name='Boutique')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('mobile_money', 'Mobile Money'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
    ]
