# Generated by Django 6.0.4 on 2026-06-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('tenants', '0004_mall_floor_mall_shop_mall'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.mall', verbose_name='Centre Commercial'),
        ),
    ]
