# Generated by Django 6.0.4 on 2026-05-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la boutique')),
                ('shop_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro')),
                ('category', models.CharField(choices=[('clothing', 'Vêtements & Mode'), ('food', 'Restauration'), ('electronics', 'Électronique'), ('jewelry', 'Bijouterie'), ('beauty', 'Beauté & Cosmétiques'), ('sports', 'Sport & Loisirs'), ('home', 'Maison & Décoration'), ('services', 'Services'), ('supermarket', 'Supermarché'), ('pharmacy', 'Pharmacie'), ('bank', 'Banque & Finance'), ('telecom', 'Télécommunications'), ('other', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('floor', models.CharField(choices=[('rdc', 'Rez-de-chaussée'), ('1er', '1er étage'), ('2eme', '2ème étage'), ('3eme', '3ème étage')], default='rdc', max_length=10, verbose_name='Étage')),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Surface (m²)')),
                ('status', models.CharField(choices=[('occupied', 'Occupée'), ('available', 'Disponible'), ('maintenance', 'En maintenance')], default='available', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['shop_number'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name="N° Pièce d'identité")),
                ('address', models.TextField(blank=True, verbose_name='Adresse personnelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('monthly_rent', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Loyer mensuel (FCFA)')),
                ('deposit', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Caution (FCFA)')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('pending', 'En attente'), ('terminated', 'Résilié')], default='active', max_length=20, verbose_name='Statut')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions particulières')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.shop', verbose_name='Boutique')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Baux',
                'ordering': ['-start_date'],
            },
        ),
    ]
