# Generated by Django 6.0.4 on 2026-05-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='floor',
            field=models.CharField(default='Rez-de-chaussée', max_length=50, verbose_name='Étage / Niveau (Ex: 1er étage, Sous-sol...)'),
        ),
    ]
