# Generated by Django 6.0.4 on 2026-05-30 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_shop_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom (ex: Rez-de-chaussée, 1er étage)')),
                ('level', models.IntegerField(default=0, verbose_name='Niveau (pour le tri, ex: 0, 1, 2, -1)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Étage',
                'verbose_name_plural': 'Étages',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='shop',
            name='floor',
        ),
        migrations.AddField(
            model_name='shop',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='tenants.floor', verbose_name='Étage / Niveau'),
        ),
    ]
