# Generated by Django 6.0.4 on 2026-06-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_floor_alter_shop_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du centre commercial')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Centre Commercial',
                'verbose_name_plural': 'Centres Commerciaux',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='tenants.mall', verbose_name='Centre Commercial'),
        ),
        migrations.AddField(
            model_name='shop',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='tenants.mall', verbose_name='Centre Commercial'),
        ),
    ]
