# Generated by Django 6.0.4 on 2026-06-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cni_or_passport',
            field=models.FileField(blank=True, null=True, upload_to='tenants/documents/', verbose_name='CNI ou Passeport'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ninea_or_rc',
            field=models.FileField(blank=True, null=True, upload_to='tenants/documents/', verbose_name='NINEA ou Reg. Commerce'),
        ),
    ]
