# Generated by Django 6.0.4 on 2026-07-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_cni_or_passport_tenant_ninea_or_rc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mall',
            options={'ordering': ['name'], 'verbose_name': 'Propriété', 'verbose_name_plural': 'Propriétés'},
        ),
        migrations.AddField(
            model_name='mall',
            name='property_type',
            field=models.CharField(choices=[('mall', 'Centre Commercial'), ('building', 'Immeuble'), ('house', 'Maison / Villa')], default='mall', max_length=20, verbose_name='Type de propriété'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la propriété'),
        ),
    ]
