# Generated by Django 6.0.4 on 2026-05-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('zone', models.CharField(choices=[('common', 'Parties communes'), ('parking', 'Parking'), ('rdc', 'Rez-de-chaussée'), ('1er', '1er étage'), ('2eme', '2ème étage'), ('3eme', '3ème étage'), ('exterior', 'Extérieur'), ('roof', 'Toiture'), ('elevator', 'Ascenseur'), ('electrical', 'Installation électrique'), ('plumbing', 'Plomberie')], max_length=50, verbose_name='Zone')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='new', max_length=20, verbose_name='Statut')),
                ('assigned_to', models.CharField(blank=True, max_length=200, verbose_name='Assigné à')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Coût estimé (FCFA)')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Coût réel (FCFA)')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Date planifiée')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
            ],
            options={
                'verbose_name': 'Demande de maintenance',
                'verbose_name_plural': 'Demandes de maintenance',
                'ordering': ['-created_at'],
            },
        ),
    ]
