# Generated by Django 6.0.4 on 2026-06-02 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_mall'),
        ('maintenance', '0002_maintenancerequest_mall'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to='employees.employee', verbose_name='Employé assigné'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/photos/', verbose_name="Photo de l'incident"),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=200, verbose_name='Assigné à (Texte)'),
        ),
    ]
